### ISSUE TITLE
[BUG] Firefox background and grid gaps not working.

### ISSUE THREAD

**Issue by True-cc** [bahaistudies/conference#93]
Tested on live server at: Monday, June 14, 2021 
![image](https://user-images.githubusercontent.com/38010540/121998081-2bc7c900-cd60-11eb-8ab0-2475ec2b9563.png)
Suggestion: set a background because some web browsers (such as firefox) set a default background if none are defined (I think).

**Comment by benaltair** [comment]
Looking like an invalid `gap` property value on the parent `ul` element.
![image](https://user-images.githubusercontent.com/17771229/122124266-e4831c00-cde3-11eb-951a-1691200ce37b.png)
From Firefox inspector. 

```css
ul {
	padding: 0;
	display: grid;
	gap: calc(--var(--icon-size)+1.25em);
	grid-auto-rows: min-content;
	align-items: center;
	justify-items: left;
}
```
There was an additional `--` before `var`: a typo. Chrome was parsing it anyways whereas Firefox disregarded the rule. Additionally, other typos around the `+` made for inconsistent handling between the two browsers. Now the rule is updated to remove typos and has better spacing. Thanks @True-cc
